game:
  width: 1100
  height: 800
  color: black
  randomSeed: 42
  prompt: true

graph:
  node:
    velocity: true
    color: blue
    radius: 10
    maxCount: 30

  edge:
    color: green
    width: 2
    maxCount: 35

forces:
  viscosity:
    active: true
    constant: 0.95
  spring:
    active: true
    constant: 0.03
    length: 50
  electric:
    active: true
    constant: 700
